### ISSUE TITLE
Mind Map ✨

### ISSUE THREAD

**Issue by anthonyshew** [anthonyshew/repo#30]
I'd love to be able to come up with a reading list or list of prerequisites for each technology for each page in the reference.

Will probably draw this out with Excalidraw first to see what it would take and then move on from there.

**Comment by AidanLaycock** [comment]
I really like this idea! 

How about having an accordion with nested checkboxes inside of it? 

(You could then save that to localStorage, and then mark any recurring reading across sections as completed e.g. For Section A & Section B I need to read Article 1, when I click completed on Section A, it shows as checked on Section B as well)

**Comment by anthonyshew** [comment]
Blocked by #32

Edit: Done!

**Comment by anthonyshew** [comment]
I drew it awhile ago. https://twitter.com/anthonysheww/status/1691824634977485246 Now to make some sort of implementation...

**Comment by anthonyshew** [comment]
Did some exploring, let's use React Flow. Goin' in...
