### ISSUE TITLE
Design system for diagrams and imagery

### ISSUE THREAD

**Issue by anthonyshew** [anthonyshew/repo#32]

**Comment by AidanLaycock** [comment]
Diagrams: 

It may be worth looking into leveraging Mermaid for this? (https://mermaid.live/) As that might give some additional accessibility benefits and it should just work in MDX.

Also as a good place to hold this, Laracasts has a rightclick handler on their logo which takes you to - https://assets.laracasts.com/, which would be a good place to hold a 'manual' on design, branding and tone for writing.

**Comment by anthonyshew** [comment]
I'm less concerned with the actual implementation than the designs themselves on this. Once I figure out *what* I want these visuals to be, I'll work more on *how*.
