### ISSUE TITLE
[Question] Is `baseUrl` needed in `tsconfig.json` ?

### ISSUE THREAD

**Issue by jeniabrook** [anthonyshew/repo#59]
First of all big fan of what are you doing with "Monorepo Maestros"!

I've read your TypeScript docs and wondering if we need to have a `baseUrl` in the `tsconfig.json` file that references `@repo/tsconfig`?

Meaning:
```json
// packages/logger/tsconfig.json file
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "@repo/tsconfig/base.json", // Using our base config!
  "compilerOptions": {
    "tsBuildInfoFile": "node_modules/.cache/tsbuildinfo.json",
    "baseUrl": ".",
  },
  "include": ["."],
  "exclude": ["node_modules"]
}
```

If we don't need it, in which scenarios do we need it in monorepo? In conjunction with `paths` maybe?

**Comment by anthonyshew** [comment]
You're correct, `baseUrl` tends to get used with `paths` but it also can be used for non-relative module names. Documentation here: https://www.typescriptlang.org/tsconfig#baseUrl
