### ISSUE TITLE
The suspense is killing me

### ISSUE THREAD

**Issue by erakor** [anthonyshew/repo#70]
We'll never know where to add your scripts. Maybe the answer was "in our hearts" all along.
https://github.com/anthonyshew/maestros/blob/fa38906f99dadcf1a2ed972022c43f4e30909ecc/apps/maestros/content/maestros/lessons/guardrails/eslint.mdx#L183

**Comment by anthonyshew** [comment]
🤦 

Thanks for letting me know. Fix incoming!

**Comment by erakor** [comment]
Thank you for this content. This is amazing!
