### ISSUE TITLE
Outdated/Incorrect `turbo generate workspace` command

### ISSUE THREAD

**Issue by euan-cowie** [anthonyshew/repo#97]
https://github.com/anthonyshew/maestros/blob/7ea2049e141ecdfa31073f6dcfef0711a5379f4b/apps/maestros/content/maestros/lessons/try-it-out/thinking-in-graphs.mdx#L49

The above line did not work for me when trying to use your unofficial turbo studio graphing tool. I checked the docs for `turbo generate workspace` and it appears you need to provide the GitHub URL or file location to the '-c- argument. 

N.B. Love the studio tool by the way. Very handy for visualising a growing monorepo!

**Comment by anthonyshew** [comment]
Fixed in #98. Thanks!
